<?xml version="1.0"?>

<robot name="auto_turret_vehicle" 
xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="body_link_x_dim" value="1"/>
<xacro:property name="body_link_y_dim" value="0.6"/>
<xacro:property name="body_link_z_dim" value="0.3"/>

<xacro:property name="wheel_link_radius" value="0.15"/>
<xacro:property name="wheel_link_length" value="0.1"/>
<xacro:property name="wheel_link_z_location" value="-0.1"/>

<xacro:property name="body_density" value="2710.0"/>
<xacro:property name="wheel_density" value="2710.0"/>

<xacro:property name="pi_const" value="3.14159265"/>

<xacro:property name="body_mass"
value="${body_density*body_link_x_dim*body_link_y_dim*body_link_z_dim}"/>
<xacro:property name="wheel_mass"
value="${wheel_density*pi_const*wheel_link_radius*wheel_link_radius*wheel_link_length}"/>

<xacro:property name="Iz_wheel" 
value="${0.5*wheel_mass*wheel_link_radius*wheel_link_radius}"/>
<xacro:property name="I_wheel" 
value="${(1.0/12.0)*wheel_mass*(3.0*wheel_link_radius*wheel_link_radius+wheel_link_length*wheel_link_length)}"/>

<xacro:macro name="inertia_wheel">
    <inertial>
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <mass value="${wheel_mass}"/>
    <inertia ixx="${I_wheel}" ixy="0.0" ixz="0.0" iyy="${I_wheel}" iyz="0.0" izz="${Iz_wheel}"/>
    </inertial>
</xacro:macro>


<xacro:include filename="$(find mobile_robot)/model/robot.gazebo"/>

<link name="dummy">
</link>

<joint name="dummy_joint" type="fixed">
    <parent link="dummy"/>
    <child link="body_link"/>
</joint>

<link name="body_link">
    <visual>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
        <geometry>
            <box size="${body_link_x_dim} ${body_link_y_dim} ${body_link_z_dim}"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass}"/>
        <inertia 
        ixx="${(1.0/12.0)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_z_dim*body_link_z_dim)}" 
        ixy="0" ixz="0" iyy="${(1.0/12.0)*body_mass*(body_link_x_dim*body_link_x_dim+body_link_z_dim*body_link_z_dim)}" 
        iyz="0" izz="${(1.0/12.0)*body_mass*(body_link_y_dim*body_link_y_dim+body_link_x_dim*body_link_x_dim)}" />
    </inertial>
</link>

<joint name="wheel1_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel1_link"/>
    <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel1_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </visual>

    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </collision>

    <xacro:inertia_wheel/>
</link>

<joint name="wheel2_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel2_link"/>
    <origin xyz="${-body_link_x_dim/2+1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel2_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </visual>

    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </collision>

    <xacro:inertia_wheel/>
</link>

<joint name="wheel3_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel3_link"/>
    <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${-body_link_y_dim/2-wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel3_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </visual>

    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </collision>

    <xacro:inertia_wheel/>
</link>
    
<joint name="wheel4_joint" type="continuous">
    <parent link="body_link"/>
    <child link="wheel4_link"/>
    <origin xyz="${body_link_x_dim/2-1.2*wheel_link_radius} ${body_link_y_dim/2+wheel_link_length/2} ${wheel_link_z_location}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000" velocity="1000"/>
    <dynamics damping="1.0" friction="1.0"/>
</joint>

<link name="wheel4_link">
    <visual>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </visual>

    <collision>
        <origin rpy="1.570795 0 0" xyz="0 0 0"/>
        <geometry>
            <cylinder length="${wheel_link_length}" radius="${wheel_link_radius}"/>
        </geometry>
    </collision>

    <xacro:inertia_wheel/>
</link>



<joint name="turret_joint" type="continuous">
    <parent link="body_link"/>
    <child link="turret_link"/>
    <origin xyz="0 0 0.35" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
</joint>

<link name="turret_link">
    <visual>
        <geometry>
            <box size="${body_link_x_dim/1.5} ${body_link_y_dim} 0.4"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
        <geometry>
            <box size="${body_link_x_dim/1.5} ${body_link_y_dim} 0.2"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass/7}"/>
        <inertia 
        ixx="${(1.0/12.0)*body_mass/3*(body_link_y_dim/2*body_link_y_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        ixy="0" ixz="0" iyy="${(1.0/12.0)*body_mass/3*(body_link_x_dim/2*body_link_x_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        iyz="0" izz="${(1.0/12.0)*body_mass/3*(body_link_y_dim/2*body_link_y_dim/2+body_link_x_dim/2*body_link_x_dim/2)}" />
    </inertial>
</link>

<joint name="gun_joint" type="fixed">
    <parent link="turret_link"/>
    <child link="gun_link"/>
    <origin xyz="${body_link_x_dim/1.0} 0 0" rpy="0 0 0"/>
    <axis xyz="0 0 0"/>
</joint>

<link name="gun_link">
    <visual>
        <geometry>
            <cylinder length="${body_link_x_dim*1.5}" radius="0.05"/>
        </geometry>
        <origin rpy="0 ${pi_const/2} 0" xyz="0 0 0"/>
    </visual>

    <collision>
        <geometry>
            <box size="${body_link_x_dim*1.5} 0.1 0.1"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass/10}"/>
        <inertia 
        ixx="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        ixy="0" ixz="0" iyy="${(1.0/12.0)*body_mass/5*(body_link_x_dim/2*body_link_x_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        iyz="0" izz="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_x_dim/2*body_link_x_dim/2)}" />
    </inertial>
</link>



<joint name="front_camera_joint" type="fixed">
    <parent link="turret_link"/>
    <child link="front_camera_link"/>
    <origin xyz="0.35 0 0.1" rpy="0 0 0"/>
</joint>

<link name="front_camera_link">
    <visual>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass/30}"/>
        <inertia 
        ixx="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        ixy="0" ixz="0" iyy="${(1.0/12.0)*body_mass/5*(body_link_x_dim/2*body_link_x_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        iyz="0" izz="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_x_dim/2*body_link_x_dim/2)}" />
    </inertial>
</link>

<joint name="front_camera_optical_joint" type="fixed">
    <parent link="front_camera_link"/>
    <child link="front_camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-pi_const/2} 0 ${-pi_const/2}"/>
</joint>

<link name="front_camera_link_optical">
</link>


<joint name="right_camera_joint" type="fixed">
    <parent link="turret_link"/>
    <child link="right_camera_link"/>
    <origin xyz="0 -0.32 0.1" rpy="0 0 ${-pi_const/2}"/>
</joint>

<link name="right_camera_link">
    <visual>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass/30}"/>
        <inertia 
        ixx="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        ixy="0" ixz="0" iyy="${(1.0/12.0)*body_mass/5*(body_link_x_dim/2*body_link_x_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        iyz="0" izz="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_x_dim/2*body_link_x_dim/2)}" />
    </inertial>
</link>

<joint name="right_camera_optical_joint" type="fixed">
    <parent link="right_camera_link"/>
    <child link="right_camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-pi_const/2} 0 ${-pi_const/2}"/>
</joint>

<link name="right_camera_link_optical">
</link>


<joint name="rear_camera_joint" type="fixed">
    <parent link="turret_link"/>
    <child link="rear_camera_link"/>
    <origin xyz="-0.35 0 0.1" rpy="0 0 ${pi_const}"/>
</joint>

<link name="rear_camera_link">
    <visual>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass/30}"/>
        <inertia 
        ixx="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        ixy="0" ixz="0" iyy="${(1.0/12.0)*body_mass/5*(body_link_x_dim/2*body_link_x_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        iyz="0" izz="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_x_dim/2*body_link_x_dim/2)}" />
    </inertial>
</link>

<joint name="rear_camera_optical_joint" type="fixed">
    <parent link="rear_camera_link"/>
    <child link="rear_camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-pi_const/2} 0 ${-pi_const/2}"/>
</joint>

<link name="rear_camera_link_optical">
</link>


<joint name="left_camera_joint" type="fixed">
    <parent link="turret_link"/>
    <child link="left_camera_link"/>
    <origin xyz="0 0.32 0.1" rpy="0 0 ${pi_const/2}"/>
</joint>

<link name="left_camera_link">
    <visual>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </visual>

    <collision>
        <geometry>
            <box size="0.05 0.05 0.05"/>
        </geometry>
        <origin rpy="0 0 0" xyz="0 0 0"/>
    </collision>

    <inertial>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <mass value="${body_mass/30}"/>
        <inertia 
        ixx="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        ixy="0" ixz="0" iyy="${(1.0/12.0)*body_mass/5*(body_link_x_dim/2*body_link_x_dim/2+body_link_z_dim/2*body_link_z_dim/2)}" 
        iyz="0" izz="${(1.0/12.0)*body_mass/5*(body_link_y_dim/2*body_link_y_dim/2+body_link_x_dim/2*body_link_x_dim/2)}" />
    </inertial>
</link>

<joint name="left_camera_optical_joint" type="fixed">
    <parent link="left_camera_link"/>
    <child link="left_camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-pi_const/2} 0 ${-pi_const/2}"/>
</joint>

<link name="left_camera_link_optical">
</link>


<ros2_control name="RobotSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>

        <joint name="turret_joint">
            <command_interface name="position">
                <param name="min">-2.879793</param>
                <param name="max">2.879793</param>
            </command_interface>
            <state_interface name="position"/>
        </joint>
</ros2_control>
</robot>  
